spring:
  application:
    name: happy-mq
  rabbitmq:
    host: 47.104.147.118
    username: happy
    password: L123456
    port: 5672
    template:
      mandatory: true  #true时,当按照key匹配失败时,通过回调函数发送消息给生产者
    publisher-confirms: true
    publisher-returns: true

#设置交换器名称
mq:
  config:
    exchange: test.topic
